name: main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: CI
        run: make ci
      - name: Spell Check Repo
        uses: crate-ci/typos@v1.48.0
